[book]
title = "Little Code"
authors = ["azusachino"]
description = "Practicing Algorithm and Data Structure"
language = "en"
multilingual = true
src = "src"

[build]
create-missing = false           # whether or not to create missing pages
use-default-preprocessors = true # use the default preprocessors

[output.html]
git-repository-url = "https://github.com/azusachino/little-code"
git-repository-icon = "fa-github"
