[package]
name = "little_code"
version = "0.0.1"
authors = ["azusachino <azusachino@duck.com>"]
edition = "2021"
repository = "https://github.com/azusachino/little-code"

[dependencies]
anyhow = "1.0"
clap = { version = "4.3", features = ["derive"] }
